Use Docker Compose v2

diff --git a/bin/start_conjur b/bin/start_conjur
--- a/bin/start_conjur
+++ b/bin/start_conjur
@@ -5,7 +5,7 @@ cd "$(dirname "$0")/.." || (echo "Could not cd to parent dir"; exit 1)
 
 cleanup() {
   echo "Cleaning up..."
-  docker-compose rm --stop --force -v
+  docker compose rm --stop --force -v
 }
 
 make_network(){
@@ -19,14 +19,14 @@ if [ "$1" == "-d" ]; then
   shift
 fi
 
-trap 'echo "ERROR: Test script encountered an error!"; docker-compose logs; cleanup' ERR
+trap 'echo "ERROR: Test script encountered an error!"; docker compose logs; cleanup' ERR
 cleanup
 
 make_network
 echo "Building services..."
-docker-compose build pg conjur conjur-https
+docker compose build pg conjur conjur-https
 
 # Start Conjur server
 echo "Starting Conjur..."
-docker-compose up -d conjur conjur-https
-docker-compose exec -T conjur conjurctl wait
+docker compose up -d conjur conjur-https
+docker compose exec -T conjur conjurctl wait
